export type Winner = {
  ageGroup: string;
  team: string;
  town: string;
};

export type HallOfFameYear = {
  year: number;
  winners: Winner[];
};

export const hallOfFame: HallOfFameYear[] = [
  {
    year: 2025,
    winners: [
      { ageGroup: "Boys U9", team: "The Academy Player", town: "West London" },
      { ageGroup: "Boys U10", team: "Wallsend Boys", town: "Newcastle" },
      { ageGroup: "Boys U11", team: "The Academy Player", town: "London" },
      { ageGroup: "Boys U12", team: "Tilbury Blacks FC", town: "Essex" },
      { ageGroup: "Boys U13", team: "Santos Panther Volts", town: "Northampton" },
      { ageGroup: "Boys U14", team: "Santos Panthers", town: "Northampton" },
      { ageGroup: "Boys U15", team: "Redditch United", town: "Birmingham" },
      { ageGroup: "Boys U16", team: "Rushall Olympic", town: "Walsall" },
      { ageGroup: "Boys U18", team: "Rushall Olympic", town: "Walsall" },
      { ageGroup: "Girls GU12", team: "Procision Reading FC", town: "Reading" },
      { ageGroup: "Girls GU13", team: "Shenley FC Lionesses", town: "Bedford" },
      { ageGroup: "Girls GU14", team: "Hutton Hawk", town: "Essex" },
      { ageGroup: "Girls GU15", team: "Panthera FC", town: "Barnet" },
      { ageGroup: "Girls GU16", team: "Leatherhead youth Girls", town: "Leatherhead" },
      { ageGroup: "Girls GU18", team: "HFR Haringey", town: "North London" },
    ],
  },
  {
    year: 2024,
    winners: [
      { ageGroup: "Boys U9", team: "Aylestone Park FC", town: "Leicester" },
      { ageGroup: "Boys U10", team: "ESC Admiral", town: "Liverpool" },
      { ageGroup: "Boys U11", team: "APB Wingate", town: "Barnet" },
      { ageGroup: "Boys U12", team: "Cheshunt FC", town: "Cheshunt" },
      { ageGroup: "Boys U13", team: "South Park Allstars", town: "Reigate" },
      { ageGroup: "Boys U14", team: "Bracknell Town", town: "Bracknell" },
      { ageGroup: "Boys U15", team: "Santos Panthers", town: "Northampton" },
      { ageGroup: "Boys U16", team: "Rushall Olympic", town: "Walsall" },
      { ageGroup: "Boys U18", team: "Wortley Juniors", town: "Leeds" },
      { ageGroup: "Girls GU12", team: "Sittingbourne Ladies", town: "Sittingbourne" },
      { ageGroup: "Girls GU13", team: "Panthera FC", town: "North London" },
      { ageGroup: "Girls GU14", team: "Panthera FC", town: "North London" },
      { ageGroup: "Girls GU15", team: "Cambridge City Ladies", town: "Cambridge" },
      { ageGroup: "Girls GU16", team: "HFR Haringey", town: "North London" },
      { ageGroup: "Girls GU18", team: "HFR Haringey", town: "North London" },
    ],
  },
  {
    year: 2023,
    winners: [
      { ageGroup: "Boys U9", team: "South Liverpool FC", town: "Liverpool" },
      { ageGroup: "Boys U10", team: "West Bridgford Colts", town: "Nottingham" },
      { ageGroup: "Boys U11", team: "Rakers Blue", town: "Wirral" },
      { ageGroup: "Boys U12", team: "Matthiola JFC", town: "Warrington" },
      { ageGroup: "Boys U13", team: "Oxford City FC", town: "Oxford" },
      { ageGroup: "Boys U14", team: "Colney Heath FC", town: "St Albans" },
      { ageGroup: "Boys U15", team: "Lye Town", town: "Lye" },
      { ageGroup: "Boys U16", team: "Hamworthy Utd", town: "Bournemouth" },
      { ageGroup: "Boys U18", team: "Hemel Hempstead", town: "Hemel Hempstead" },
      { ageGroup: "Girls GU12", team: "Panthera FC", town: "Barnet" },
      { ageGroup: "Girls GU13", team: "Boro Rangers", town: "Middlesbrough" },
      { ageGroup: "Girls GU14", team: "Girls Utd", town: "Peterborough" },
      { ageGroup: "Girls GU15", team: "Blyth Town", town: "Blyth" },
      { ageGroup: "Girls GU16", team: "Dussindale Girls", town: "Norwich" },
      { ageGroup: "Girls GU18", team: "HFR Haringey", town: "North London" },
    ],
  },
  {
    year: 2022,
    winners: [
      { ageGroup: "Boys U9", team: "MCR Sports", town: "Manchester" },
      { ageGroup: "Boys U10", team: "Manchester Corinthians", town: "Manchester" },
      { ageGroup: "Boys U11", team: "Stockport County", town: "Stockport" },
      { ageGroup: "Boys U12", team: "L4 Barca", town: "Liverpool" },
      { ageGroup: "Boys U13", team: "Cheshunt FC", town: "Cheshunt" },
      { ageGroup: "Boys U14", team: "Coventry United", town: "Coventry" },
      { ageGroup: "Boys U15", team: "Thorpe Wood Rangers", town: "Peterborough" },
      { ageGroup: "Boys U16", team: "Boro Rangers", town: "Middlebrough" },
      { ageGroup: "Boys U18", team: "Seaton Carew", town: "Hartlepool" },
      { ageGroup: "Girls GU12", team: "Boro Rangers", town: "Middlesbrough" },
      { ageGroup: "Girls GU13", team: "Girls United", town: "Peterborough" },
      { ageGroup: "Girls GU14", team: "HFR Haringey", town: "Haringey" },
      { ageGroup: "Girls GU15", team: "HFR Haringey", town: "Haringey" },
      { ageGroup: "Girls GU16", team: "HFR Haringey", town: "Haringey" },
      { ageGroup: "Girls GU18", team: "HFR Haringey", town: "Haringey" },
    ],
  },
  {
    year: 2021,
    winners: [
      { ageGroup: "Boys U9", team: "AS Eastbourne", town: "Eastbourne" },
      { ageGroup: "Boys U10", team: "Platinum Milan", town: "Liverpool" },
      { ageGroup: "Boys U11", team: "Pendle Forest Warriors", town: "Pendle" },
      { ageGroup: "Boys U12", team: "Enfield Rangers", town: "Enfield" },
      { ageGroup: "Boys U13", team: "Manchester Corinthians", town: "Manchester" },
      { ageGroup: "Boys U14", team: "AS Eastbourne", town: "Eastbourne" },
      { ageGroup: "Boys U15", team: "Berkhamsted FC", town: "Berkhamsted" },
      { ageGroup: "Boys U16", team: "Tyne and Wear HSG", town: "Tyne and Wear" },
      { ageGroup: "Boys U17", team: "Basford Utd", town: "Nottingham" },
      { ageGroup: "Girls GU12", team: "Girls United", town: "Peterborough" },
      { ageGroup: "Girls GU13", team: "HFR Haringey", town: "North London" },
      { ageGroup: "Girls GU14", team: "Winstanley Warriors", town: "Wigan" },
      { ageGroup: "Girls GU15", team: "HFR Haringey", town: "North London" },
      { ageGroup: "Girls GU16", team: "HFR Haringey", town: "Haringey" },
      { ageGroup: "Girls Gu17", team: "Plymouth Aspire Girls", town: "Plymouth" },
    ],
  },
  {
    year: 2019,
    winners: [
      { ageGroup: "Boys U9", team: "West Bromwich", town: "West Brom" },
      { ageGroup: "Boys U10", team: "Enfield Rangers", town: "Enfield" },
      { ageGroup: "Boys U11", team: "Coventry Utd", town: "Coventry" },
      { ageGroup: "Boys U12", team: "Ruislip Rangers", town: "Harrow" },
      { ageGroup: "Boys U13", team: "Solihull Academy", town: "Solihull" },
      { ageGroup: "Boys U14", team: "London Colney Colts", town: "St Albans" },
      { ageGroup: "Boys U15", team: "Portland Sports", town: "Dorset" },
      { ageGroup: "Boys U16", team: "Cirencester Town", town: "Gloucester" },
      { ageGroup: "Boys U17", team: "AFC Rushden & Diamonds", town: "Nottingham" },
      { ageGroup: "Girls GU12", team: "Cambridge City Girls", town: "Cambridge" },
      { ageGroup: "Girls GU13", team: "Blackpool Girls", town: "Blackpool" },
      { ageGroup: "Girls GU14", team: "Haringey Girls", town: "North London" },
      { ageGroup: "Girls GU15", team: "Derby County", town: "Derby" },
      { ageGroup: "Girls GU16", team: "London Bees Academy", town: "North London" },
      { ageGroup: "Girls Gu17", team: "Washington Lionesses", town: "Washington" },
    ],
  },
  {
    year: 2018,
    winners: [
      { ageGroup: "Boys U9", team: "London Colney Colts", town: "St Albans" },
      { ageGroup: "Boys U10", team: "Coventry Utd", town: "Coventry" },
      { ageGroup: "Boys U11", team: "Silksworth CW", town: "Sunderland" },
      { ageGroup: "Boys U12", team: "AS Eastbourne", town: "Eastbourne" },
      { ageGroup: "Boys U13", team: "Aylestone Park Youth", town: "Leicester" },
      { ageGroup: "Boys U14", team: "Fleur De Lys", town: "Portsmouth" },
      { ageGroup: "Boys U15", team: "Ipro Football", town: "Marlow" },
      { ageGroup: "Boys U16", team: "Ipro Football Tigers", town: "Marlow" },
      { ageGroup: "Girls GU12", team: "Pro FA FC", town: "North London" },
      { ageGroup: "Girls GU13", team: "Cambridge City Girls", town: "Cambridge" },
      { ageGroup: "Girls GU14", team: "Washington Lionesses", town: "Washington" },
      { ageGroup: "Girls GU15", team: "Central Girls Academy", town: "Falkirk" },
      { ageGroup: "Girls GU16", team: "Washington Lionesses", town: "Washington" },
      { ageGroup: "Girls Gu17", team: "Blofield Utd", town: "Norwich" },
    ],
  },
  {
    year: 2017,
    winners: [
      { ageGroup: "Boys U11", team: "Lowdham Colts", town: "Nottingham" },
      { ageGroup: "Boys U12", team: "Ifield Galaxy", town: "Crawley" },
      { ageGroup: "Boys U13", team: "Stakeford Juniors", town: "Northumberland" },
      { ageGroup: "Boys U14", team: "Predator", town: "Liverpool" },
      { ageGroup: "Boys U15", team: "Studley Juniors", town: "South Birmingham" },
      { ageGroup: "Boys U16", team: "Mags FC", town: "Liverpool" },
      { ageGroup: "Girls GU13", team: "Preston North End", town: "Preston" },
      { ageGroup: "Girls GU14", team: "Hendon FC Girls", town: "North London" },
      { ageGroup: "Girls GU15", team: "Washington Girls", town: "Washington" },
      { ageGroup: "Girls GU16", team: "Blofield United", town: "Norfolk" },
      { ageGroup: "Girls Gu17", team: "Sprowston Girls", town: "Norwich" },
    ],
  },
  {
    year: 2016,
    winners: [
      { ageGroup: "Boys U11", team: "Aylestone Park Youth", town: "Leicester" },
      { ageGroup: "Boys U12", team: "VCD Athletic", town: "Crawley" },
      { ageGroup: "Boys U13", team: "Hove Riverdale", town: "Brighton" },
      { ageGroup: "Boys U14", team: "Kellingley Welfare Juniors", town: "Leeds" },
      { ageGroup: "Boys U15", team: "Concord Rangers", town: "Essex" },
      { ageGroup: "Boys U16", team: "Ryan FC", town: "East London" },
      { ageGroup: "Girls GU13", team: "Washington AFC", town: "Washington" },
      { ageGroup: "Girls GU14", team: "Tilehurst Panthers", town: "Reading" },
      { ageGroup: "Girls GU15", team: "Preston North End", town: "Preston" },
      { ageGroup: "Girls GU16", team: "Central Girls Academy", town: "Falkirk" },
      { ageGroup: "Girls Gu17", team: "Central Girls Academy", town: "Falkirk" },
    ],
  },
  {
    year: 2015,
    winners: [
      { ageGroup: "Boys U11", team: "Aylestone Park Youth", town: "Leicester" },
      { ageGroup: "Boys U12", team: "Bournvile Warriors", town: "Birmingham" },
      { ageGroup: "Boys U13", team: "Mickleover Sports", town: "Derby" },
      { ageGroup: "Boys U14", team: "Felixstowe & Walton", town: "Felixstowe" },
      { ageGroup: "Boys U15", team: "Sileby Juniors", town: "Leicester" },
      { ageGroup: "Boys U16", team: "Cove Youth United", town: "Farnborough" },
      { ageGroup: "Girls GU13", team: "Washington AFC", town: "Washington" },
      { ageGroup: "Girls GU14", team: "Coundon Court Girls", town: "Coventry" },
      { ageGroup: "Girls GU15", team: "Frome Town", town: "Bath" },
      { ageGroup: "Girls GU16", team: "Farsley AFC Ladies", town: "Leeds" },
      { ageGroup: "Girls Gu17", team: "Mill Lane Girls", town: "Hull" },
    ],
  },
  {
    year: 2014,
    winners: [
      { ageGroup: "Boys U11", team: "Newcastle City Juniors", town: "Newcastle" },
      { ageGroup: "Boys U12", team: "Pontefract Collieries", town: "Leeds" },
      { ageGroup: "Boys U13", team: "Carlton Town", town: "Nottingham" },
      { ageGroup: "Boys U14", team: "Broxbourne Borough", town: "Broxbourne" },
      { ageGroup: "Boys U15", team: "AFC Wembley", town: "North West London" },
      { ageGroup: "Boys U16", team: "Buckhurst Hill", town: "Essex" },
      { ageGroup: "Girls U12", team: "Washington Lionesses", town: "Washington" },
      { ageGroup: "Girls GU13", team: "AFC Manchester", town: "Manchester" },
      { ageGroup: "Girls GU14", team: "Central Girls Academy", town: "Falkirk" },
      { ageGroup: "Girls GU15", team: "Mill Lane United Girls", town: "Hull" },
      { ageGroup: "Girls GU16", team: "Mill Lane United Girls", town: "Hull" },
      { ageGroup: "Girls Gu17", team: "Cramlington Girls", town: "Newcastle" },
    ],
  },
  {
    year: 2013,
    winners: [
      { ageGroup: "Boys U11", team: "Groby Juniors", town: "Leicester" },
      { ageGroup: "Boys U12", team: "Eastleigh Juniors", town: "Southampton" },
      { ageGroup: "Boys U13", team: "AFC Wembley", town: "North West London" },
      { ageGroup: "Boys U14", team: "Parkfield Youth", town: "Harrow" },
      { ageGroup: "Boys U15", team: "Washington United", town: "Sunderland" },
      { ageGroup: "Boys U16", team: "Kidderminster Harriers", town: "Kidderminster" },
      { ageGroup: "Girls GU14", team: "Huddersfield Town Girls", town: "Huddersfield" },
      { ageGroup: "Girls GU15", team: "Mill Lane United Girls", town: "Hull" },
      { ageGroup: "Girls GU16", team: "Lewes Girls", town: "Lewes" },
      { ageGroup: "Girls Gu17", team: "Birkdale United Girls", town: "Southport" },
    ],
  },
  {
    year: 2012,
    winners: [
      { ageGroup: "Boys U11", team: "Pro Future", town: "Blackburn" },
      { ageGroup: "Boys U12", team: "Hessle Rangers", town: "Hull" },
      { ageGroup: "Boys U13", team: "Blidworth Welfare", town: "Nottingham" },
      { ageGroup: "Boys U14", team: "Ulverley Hawks", town: "Birmingham" },
      { ageGroup: "Boys U15", team: "Burton Central", town: "Derby" },
      { ageGroup: "Boys U16", team: "Harrow and Wieldstone", town: "Harrow" },
      { ageGroup: "Girls GU14", team: "Stretton Swifts", town: "Burton" },
      { ageGroup: "Girls GU16", team: "Leicester City Ladies", town: "Leicester" },
    ],
  },
  {
    year: 2011,
    winners: [
      { ageGroup: "Boys U11", team: "Shifnal Harriers", town: "Telford" },
      { ageGroup: "Boys U12", team: "Woodbridge Town", town: "Ipswich" },
      { ageGroup: "Boys U13", team: "Dunstable Town", town: "Dunstable" },
      { ageGroup: "Boys U14", team: "Highfield Rangers", town: "Leicester" },
      { ageGroup: "Boys U15", team: "Whetstone Rangers", town: "Leicester" },
      { ageGroup: "Boys U16", team: "Netherton United", town: "Peterborough" },
      { ageGroup: "Girls GU14", team: "Blackpool FC Ladies", town: "Blackpool" },
      { ageGroup: "Girls GU16", team: "Mersey Girls", town: "Liverpool" },
    ],
  },
  {
    year: 2010,
    winners: [
      { ageGroup: "Boys U14", team: "Woodfood Youth FC", town: "Essex" },
      { ageGroup: "Boys U15", team: "Wingate and Finchley", town: "London" },
    ],
  },
  {
    year: 2009,
    winners: [
      { ageGroup: "Boys U15", team: "Harvesters FC", town: "St. Albans" },
    ],
  },
];

export const hallOfFameYears = hallOfFame.map((y) => y.year).sort((a, b) => b - a);

export function getHallOfFameByYear(year: number) {
  return hallOfFame.find((y) => y.year === year);
}
